# Generated by Django 5.2.7 on 2025-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="google_analytics_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
