# Generated by Django 5.2.7 on 2025-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesettings_google_analytics_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
