# Generated by Django 5.2.7 on 2025-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="credential_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="case_study_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="live_demo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skillarea",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
