# Generated by Django 5.2.7 on 2025-10-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_blogcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile/banners/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume_pdf",
            field=models.FileField(blank=True, null=True, upload_to="profile/resume/"),
        ),
    ]
