# Generated by Django 5.2.7 on 2025-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_profile_banner_profile_resume_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillarea",
            name="color",
            field=models.CharField(
                default="bg-blue-500",
                help_text="Tailwind color class (e.g., bg-blue-500)",
                max_length=50,
            ),
        ),
    ]
