# Generated by Django 5.2.7 on 2025-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_skillarea_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Specific technologies, tools, or methodologies",
                null=True,
            ),
        ),
    ]
