# Generated by Django 5.2.7 on 2025-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_skill_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for searching/filtering",
                max_length=200,
            ),
        ),
    ]
