# Generated by Django 5.2.7 on 2025-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_skill_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="experience/logos/"
            ),
        ),
    ]
