# Generated by Django 5.2.7 on 2025-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_experience_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
