# Generated by Django 5.2.7 on 2025-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_experience_company_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
