# Generated by Django 5.2.7 on 2025-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_experience_employment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Key responsibilities and achievements", null=True
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="technologies",
            field=models.TextField(
                blank=True, help_text="Technologies and tools utilized", null=True
            ),
        ),
    ]
