# Generated by Django 5.2.7 on 2025-10-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_experience_responsibilities_experience_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="achievements",
            field=models.TextField(
                blank=True, help_text="Notable accomplishments", null=True
            ),
        ),
    ]
