# Generated by Django 5.2.7 on 2025-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_experience_achievements"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief project summary for listings",
                null=True,
            ),
        ),
    ]
