# Generated by Django 5.2.7 on 2025-10-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_project_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
