# Generated by Django 5.2.7 on 2025-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
