# Generated by Django 5.2.7 on 2025-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_project_status_project_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
