# Generated by Django 5.2.7 on 2025-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_project_team_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
