# Generated by Django 5.2.7 on 2025-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
