# Generated by Django 5.2.7 on 2025-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_project_demo_link_project_github_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for searching/filtering",
                max_length=200,
            ),
        ),
    ]
