# Generated by Django 5.2.7 on 2025-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
