# Generated by Django 5.2.7 on 2025-10-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="authority_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
