# Generated by Django 5.2.7 on 2025-10-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_certification_authority_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="icon_class",
            new_name="icon",
        ),
    ]
