# Generated by Django 5.2.7 on 2025-10-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_rename_icon_class_certification_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="icon",
            new_name="icon_class",
        ),
    ]
