# Generated by Django 5.2.7 on 2025-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_rename_icon_certification_icon_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="skills",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated skills for searching/filtering",
                max_length=200,
            ),
        ),
    ]
